package com.ankje.mybatis.study.model.lab7.mapper;

import com.ankje.mybatis.study.model.lab7.po.Orders;
import com.ankje.mybatis.study.model.lab7.po.OrdersExample;
import java.util.List;

import com.ankje.mybatis.study.model.lab7.po.UserExample;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    List<Orders> selectByExample(OrdersExample example);

    List<Orders> selectByWhereWithUser(@Param("a") OrdersExample a, @Param("b") UserExample b);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    int updateByPrimaryKey(Orders record);
}