package com.ankje.mybatis.study.model.lab7.po;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table f_user
 */
public class FUser {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.create_by
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.create_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer createTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.update_by
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer updateBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.update_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer updateTime;

    /**
     * Database Column Remarks:
     *   删除状态  0正常 1删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.del
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Boolean del;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.remark
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.create_date
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String createDate;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.update_date
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String updateDate;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.realname
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String realname;

    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.username
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.pwd
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String pwd;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.mobile
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   性别 1男， 2女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.gender
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Boolean gender;

    /**
     * Database Column Remarks:
     *   身份证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.idcard
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String idcard;

    /**
     * Database Column Remarks:
     *   头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.avatar
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String avatar;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.birthday
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   微信openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.openid_wx
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String openidWx;

    /**
     * Database Column Remarks:
     *   QQopenid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.openid_qq
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String openidQq;

    /**
     * Database Column Remarks:
     *   名字首字母
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.letter
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String letter;

    /**
     * Database Column Remarks:
     *   最后登录IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.last_login_ip
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String lastLoginIp;

    /**
     * Database Column Remarks:
     *   最后登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.last_login_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer lastLoginTime;

    /**
     * Database Column Remarks:
     *   登录次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.total_login
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer totalLogin;

    /**
     * Database Column Remarks:
     *   省份ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.province_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer provinceId;

    /**
     * Database Column Remarks:
     *   城市ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.city_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer cityId;

    /**
     * Database Column Remarks:
     *   地区ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.area_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer areaId;

    /**
     * Database Column Remarks:
     *   详情地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.address
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String address;

    /**
     * Database Column Remarks:
     *   QQ号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.qq
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String qq;

    /**
     * Database Column Remarks:
     *   微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.weixin
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private String weixin;

    /**
     * Database Column Remarks:
     *   账号积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.score
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Integer score;

    /**
     * Database Column Remarks:
     *   会员状态：1正常|2冻结
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.user_state
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Byte userState;

    /**
     * Database Column Remarks:
     *   已经获取新用户50金币：1是|2否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_user.has_fetch_50_gold
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    private Boolean hasFetch50Gold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.id
     *
     * @return the value of f_user.id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.id
     *
     * @param id the value for f_user.id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.create_by
     *
     * @return the value of f_user.create_by
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.create_by
     *
     * @param createBy the value for f_user.create_by
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.create_time
     *
     * @return the value of f_user.create_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.create_time
     *
     * @param createTime the value for f_user.create_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.update_by
     *
     * @return the value of f_user.update_by
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.update_by
     *
     * @param updateBy the value for f_user.update_by
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.update_time
     *
     * @return the value of f_user.update_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.update_time
     *
     * @param updateTime the value for f_user.update_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.del
     *
     * @return the value of f_user.del
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Boolean getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.del
     *
     * @param del the value for f_user.del
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setDel(Boolean del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.remark
     *
     * @return the value of f_user.remark
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.remark
     *
     * @param remark the value for f_user.remark
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.create_date
     *
     * @return the value of f_user.create_date
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.create_date
     *
     * @param createDate the value for f_user.create_date
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.update_date
     *
     * @return the value of f_user.update_date
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.update_date
     *
     * @param updateDate the value for f_user.update_date
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.realname
     *
     * @return the value of f_user.realname
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.realname
     *
     * @param realname the value for f_user.realname
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.username
     *
     * @return the value of f_user.username
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.username
     *
     * @param username the value for f_user.username
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.pwd
     *
     * @return the value of f_user.pwd
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.pwd
     *
     * @param pwd the value for f_user.pwd
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.mobile
     *
     * @return the value of f_user.mobile
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.mobile
     *
     * @param mobile the value for f_user.mobile
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.gender
     *
     * @return the value of f_user.gender
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.gender
     *
     * @param gender the value for f_user.gender
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.idcard
     *
     * @return the value of f_user.idcard
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.idcard
     *
     * @param idcard the value for f_user.idcard
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.avatar
     *
     * @return the value of f_user.avatar
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.avatar
     *
     * @param avatar the value for f_user.avatar
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.birthday
     *
     * @return the value of f_user.birthday
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.birthday
     *
     * @param birthday the value for f_user.birthday
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.openid_wx
     *
     * @return the value of f_user.openid_wx
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getOpenidWx() {
        return openidWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.openid_wx
     *
     * @param openidWx the value for f_user.openid_wx
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setOpenidWx(String openidWx) {
        this.openidWx = openidWx == null ? null : openidWx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.openid_qq
     *
     * @return the value of f_user.openid_qq
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getOpenidQq() {
        return openidQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.openid_qq
     *
     * @param openidQq the value for f_user.openid_qq
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setOpenidQq(String openidQq) {
        this.openidQq = openidQq == null ? null : openidQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.letter
     *
     * @return the value of f_user.letter
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getLetter() {
        return letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.letter
     *
     * @param letter the value for f_user.letter
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setLetter(String letter) {
        this.letter = letter == null ? null : letter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.last_login_ip
     *
     * @return the value of f_user.last_login_ip
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.last_login_ip
     *
     * @param lastLoginIp the value for f_user.last_login_ip
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.last_login_time
     *
     * @return the value of f_user.last_login_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.last_login_time
     *
     * @param lastLoginTime the value for f_user.last_login_time
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setLastLoginTime(Integer lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.total_login
     *
     * @return the value of f_user.total_login
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getTotalLogin() {
        return totalLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.total_login
     *
     * @param totalLogin the value for f_user.total_login
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setTotalLogin(Integer totalLogin) {
        this.totalLogin = totalLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.province_id
     *
     * @return the value of f_user.province_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.province_id
     *
     * @param provinceId the value for f_user.province_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.city_id
     *
     * @return the value of f_user.city_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.city_id
     *
     * @param cityId the value for f_user.city_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.area_id
     *
     * @return the value of f_user.area_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.area_id
     *
     * @param areaId the value for f_user.area_id
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.address
     *
     * @return the value of f_user.address
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.address
     *
     * @param address the value for f_user.address
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.qq
     *
     * @return the value of f_user.qq
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.qq
     *
     * @param qq the value for f_user.qq
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.weixin
     *
     * @return the value of f_user.weixin
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.weixin
     *
     * @param weixin the value for f_user.weixin
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.score
     *
     * @return the value of f_user.score
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.score
     *
     * @param score the value for f_user.score
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.user_state
     *
     * @return the value of f_user.user_state
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Byte getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.user_state
     *
     * @param userState the value for f_user.user_state
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setUserState(Byte userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_user.has_fetch_50_gold
     *
     * @return the value of f_user.has_fetch_50_gold
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public Boolean getHasFetch50Gold() {
        return hasFetch50Gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_user.has_fetch_50_gold
     *
     * @param hasFetch50Gold the value for f_user.has_fetch_50_gold
     *
     * @mbg.generated Fri Mar 29 13:43:46 GMT+08:00 2019
     */
    public void setHasFetch50Gold(Boolean hasFetch50Gold) {
        this.hasFetch50Gold = hasFetch50Gold;
    }
}